export namespace GameMsgId { 
 export enum MsgId {
        MSG_Default = 0,
        MSG_CS_Ping = 1,
        MSG_SC_Pong = 2,
        MSG_CS_Login = 101,
        MSG_SC_Login = 102,
        MSG_CS_Register = 103,
        MSG_SC_Register = 104,
        MSG_CS_HallInfo = 111,
        MSG_SC_HallInfo = 112,
        MSG_CS_CreateRoom = 121,
        MSG_SC_CreateRoom = 122,
        MSG_CS_JoinRoom = 123,
        MSG_SC_JoinRoom = 124,
        MSG_CS_MatchRoom = 125,
        MSG_SC_MatchRoom = 126,
        MSG_CS_ExitRoom = 127,
        MSG_SC_ExitRoom = 128,
        MSG_CS_NHWCReady = 1001,
        MSG_SC_NHWCReady = 1002,
        MSG_SC_NHWCStart = 1004,
        MSG_SC_NHWCResult = 1008,
        MSG_SC_NHWCOver = 1010,
        MSG_CS_NHWCDrawClear = 1011,
        MSG_SC_NHWCDrawClear = 1012,
        MSG_CS_NHWCDrawWidth = 1013,
        MSG_SC_NHWCDrawWidth = 1014,
        MSG_CS_NHWCDrawColor = 1015,
        MSG_SC_NHWCDrawColor = 1016,
        MSG_CS_NHWCDrawPath = 1017,
        MSG_SC_NHWCDrawPath = 1018,
        MSG_CS_NHWCAnswer = 1019,
        MSG_SC_NHWCAnswer = 1020
    }
 }